plugins {
  id 'com.android.library'
  id 'expo-module-gradle-plugin'
}

group = 'expo.modules.voiceservice'
version = '0.1.0'

android {
  namespace "expo.modules.voiceservice"
  defaultConfig {
    versionCode 1
    versionName "0.1.0"
  }
  lintOptions {
    abortOnError false
  }
}

dependencies {
  // NotificationCompat / ServiceCompat
  implementation "androidx.core:core-ktx:1.13.1"
}
