// Masaüstü ve mobil istemcilerin ortak mantığı. Platforma özgü işler (bildirim, ses, pencere,
// depolama) configureClient() ile verilen ClientEnvironment üzerinden yapılır.

export { configureClient } from './configure';
export type { ClientEnvironment, KeyValueStorage, LocalFile, UploadRequest, UploadResponse } from './env';
export { api, ApiError, errorMessage, normalizeServerUrl } from './api';
export {
  forgetReactionUsers,
  loadReactionUsers,
  reactionSummary,
  reactionUsersKey,
  useReactionUsers,
  type ReactionUsersEntry,
} from './reactions';
export { recentClientErrors, reportClientError } from './errors';
export { parseReleaseNotes, type NoteBlock, type NotePart } from './releaseNotes';
export {
  baseFeedbackContext,
  canManageFeedback,
  deleteFeedback,
  feedbackApi,
  feedbackImageHeaders,
  feedbackScreenshotUrl,
  fetchFeedbackScreenshot,
  loadAllFeedback,
  loadMyFeedback,
  onOwnFeedbackUpdate,
  refreshFeedbackCount,
  submitFeedback,
  updateFeedback,
  useFeedback,
  type FeedbackDraft,
} from './feedback';
export { reportVoiceLog, SpuriousDuplicateGuard } from './voiceDiagnostics';
export {
  isStreamMuted,
  setStreamVolume,
  shownStreamVolume,
  streamAudioOutput,
  streamVolumeOf,
  toggleStreamMute,
  type StreamAudioOutput,
  type StreamAudioPrefs,
} from './streamAudio';
export {
  describeCandidate,
  describeTransport,
  formatBitrate,
  formatPercent,
  linkQuality,
  minuteTicks,
  outboundDelta,
  parseTransportStats,
  PING_HISTORY_MS,
  pingAxis,
  pushSample,
  statList,
  summarizePings,
  type CandidateInfo,
  type LinkQuality,
  type PingSample,
  type PingSummary,
  type RtcStat,
  type RtpStream,
  type StatsSource,
  type StreamView,
  type TransportStats,
  type TransportView,
} from './connectionStats';
export { gateway } from './gateway';
export {
  displayStatusOf,
  formatRemaining,
  setCustomStatus,
  setUserStatus,
  useCustomStatus,
  useSelfStatus,
  useStatus,
  type DisplayStatus,
} from './presence';
export { useSession } from './session';
export {
  channelById,
  isGuildUnread,
  isUnread,
  membersOf,
  useGuild,
  type GatewayStatus,
  type GuildState,
  type GuildStore,
  type MemberUser,
} from './guild';
export {
  createGuild,
  deleteGuild,
  guildIconUrl,
  guildInitials,
  guildInvites,
  inviteLink,
  isGuildOwner,
  joinGuild,
  leaveGuild,
  removeGuildIcon,
  uploadGuildIcon,
  useGuildList,
  useGuildUnread,
} from './guilds';
export {
  can,
  canAssignRole,
  canManageRole,
  effectivePermissions,
  isOwner,
  memberColorOf,
  memberGroups,
  outranksUser,
  overwriteState,
  permissionsInGuild,
  permissionsOf,
  roleIsBelowFor,
  rolePermissionSource,
  rolesOf,
  setOverwriteState,
  sortedRoles,
  useCan,
  useMemberColor,
  usePermissions,
  type EffectivePermissions,
  type MemberGroup,
  type OverwriteState,
  type PermissionGrant,
  type RolePermissionSource,
} from './permissions';
export {
  channelPermissionInfos,
  PERMISSION_GROUPS,
  permissionInfo,
  type PermissionGroup,
  type PermissionInfo,
} from './permissionInfo';
export { memberActions, moderation, moveTargets, type MemberActions } from './moderation';
export {
  ackChannel,
  addFiles,
  deleteMessage,
  discardMessage,
  editMessage,
  isMentioned,
  loadInitial,
  loadOlder,
  mentions,
  notifyTyping,
  removeFile,
  retryMessage,
  sendGif,
  sendMessage,
  setEditing,
  toggleReaction,
  uploadProgress,
  useMessages,
  type ChannelMessages,
  type JumpRequest,
  type LocalMessage,
  type LocalUpload,
  type ReplyDraft,
} from './messages';
export {
  cancelReply,
  clearJump,
  isOwnReplyTarget,
  jumpToMessage,
  setReplyMention,
  startReply,
} from './replies';
export {
  BROADCAST_MENTIONS,
  broadcastSuggestions,
  focusComposer,
  hasComposer,
  insertText,
  mentionInComposer,
  registerComposer,
  type BroadcastMention,
  type ComposerHandle,
} from './composer';
export {
  addDmParticipant,
  closeDm,
  createDm,
  dmBlockedReason,
  dmPartner,
  dmRecipients,
  dmTitle,
  openDirectMessage,
  renameDm,
  sortDms,
  useDmList,
  useDmUnreadCount,
  useDmUnreadTotal,
  useUnreadDms,
} from './dms';
export { attachmentUrl, avatarUrl, formatBytes, removeAvatar, uploadAvatar } from './uploads';
export {
  EMOJI_CATEGORIES,
  isJumboEmoji,
  JUMBO_EMOJI_MAX,
  QUICK_REACTIONS,
  splitEmoji,
  type EmojiCategory,
  type TextPart,
} from './emoji';
export {
  closeGifPicker,
  fitBox,
  gifEmbed,
  gifOf,
  isGiphyMedia,
  loadMoreGifs,
  openGifPicker,
  retryGifs,
  searchGifs,
  setGifQuery,
  trendingGifs,
  useFeatures,
  useGifPicker,
  type GifPickerState,
} from './gifs';
export {
  broadcastMention,
  parseInline,
  parseMarkdown,
  plainText,
  type MdBlock,
  type MdInline,
  type MdStyle,
} from './markdown';
